### ISSUE TITLE
Not working with the latest shopify template?

### ISSUE THREAD

**Issue by Mtillmann** [sanity-io/sanity-plugin-shopify-assets#5]
I believe I have the correct sanity connect app settings but the plugin always fails to retrieve any assets:

![image](https://github.com/sanity-io/sanity-plugin-shopify-assets/assets/289963/3e5e89ec-6593-4ebe-9499-c645936db9c0)

![image](https://github.com/sanity-io/sanity-plugin-shopify-assets/assets/289963/412f1774-f52f-4a67-b5bf-1505713d15c7)

Am I missing something?

**Comment by leobossmann** [comment]
+1

**Comment by Mtillmann** [comment]
> Am I missing something?    

It was an app authorization scope issue. Reinstalling the app fixed the issue
